### ISSUE TITLE
Atualizar esse exemplo com a nova versão do Next

### ISSUE THREAD

**Issue by httpiago** [httpiago/sample-react-and-next-app#2]
## Objetivo

Refazer esse simples app com toda a minha nova bagagem que adquiri desde que fiz a primeira versão há [um ano atrás, <sub>em junho de 2018</sub>](https://github.com/httpiago/sample-react-and-next-app/commit/4f2c2c918bbf20b8dc8a43d8fa960a50a7797a0c) e consequentemente verificar se é possível usar a [nova api de roteamento](https://github.com/zeit/next.js/#api-routes) do Next.js no Descontaí.

**OBS: Salvar a versão anterior em uma branch separada pra guardar de lembrança pq foi meu primeiro app em React 😍**

## Pacotes a serem usados

Não precisa usar todos mas seria bom pra treinar :)

- [TypeScript](https://www.typescriptlang.org) em TUDO.
- [Reakit](http://reakit.io/): Para deixar a interface do client amigável ao teclado.
- [Redux](https://redux.js.org): Para gerenciar o estado.
- [Axios](https://github.com/axios/axios): Para fazer requisições ao servidor.

## Roadmap

- [ ] Criar um mini banco de dados em memória usando um objeto do JavaScript.
- [ ] Fazer um sistema de autenticação funcional usando a [Routes API](https://github.com/zeit/next.js/#api-routes).
  > Tentar [sessões com cookies](https://github.com/zeit/next.js/tree/canary/examples/with-cookie-auth), caso não dê certo usar o padrão com [tokens JWT](https://jwt.io/).
- **Deve conter as rotas para:**
  - [ ] Listar tweets.
    - [ ] Ordenar por mais recentes.
    - [ ] Filtrar por usuário. (<sub>para usar no perfil dos usuários</sub>)
    - [ ] Permitir paginação kkk.
    - [ ] Retornar as informações do autor junto com cada item. (<sub>pro front não precisar fazer mtas solicitações</sub>)
  - [ ] Buscar informações de um único tweet.
    - Retornar as informações de autor junto com o tweet.
  - [ ] 🔐 Criar novos tweets.
  - [ ] 🔐 Atualizar um tweet.
  - [ ] 🔐 Deletar um tweet.
  - [ ] Listar usuários.
  - [ ] Buscar informações de um único usuário.
    - Com número de tweets publicados.
  - [ ] 🔐 Permitir atualizar informações do usuário logado.
  - [ ] 🔐 Permitir deletar o usuário que está logado.
- **Fazer o front-end**
  - [ ] Página inicial.
    - [ ] Listar tweets (Usar o comp [Rover](https://reakit.io/docs/rover/)).
    - [ ] Mostrar caixa de texto para criar novos tweets (Usar o comp [Dialog](https://reakit.io/docs/dialog/)).
    - [ ] Permitir deletar tweet se o usuário logado for o autor. (Usar o comp [Popover](https://reakit.io/docs/popover/)).
  - [ ] Página de login.
  - [ ] Página com um único tweet.
  - [ ] Página de perfil do usuário.
    - [ ] Mostrar informações dele.
    - [ ] Mostrar número de tweets.
    - [ ] Listar tweets do usuário.

## Desafios

- [ ] Permitir curtir tweets 😉.
- [ ] Permitir SEGUIR usuários 😮.
- [ ] Página de configurações 🤪.
  - [ ] Permitir mudar o username.
  - [ ] Permitir mudar a photo de perfil.
  - [ ] Permitir deletar todos os tweets da conta.
  - [ ] Permitir deletar a conta do usuário.
- [ ] Fazer o app funcionar offline 🤯.
  - https://serviceworke.rs
  - [redux-offline](https://github.com/redux-offline/redux-offline)
  - [redux-persist](https://github.com/rt2zz/redux-persist).
- [ ] Criar um sistema de notificações seria pedir demais?? 👀
